// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCzbQ2085XmGbl7XnVteh6wxg9KFXaLA8',
    appId: '1:544405577623:android:6689052af84cc70a7d6ed2',
    messagingSenderId: '544405577623',
    projectId: 'tpsmobile-f19f3',
    databaseURL: 'https://tpsmobile-f19f3-default-rtdb.firebaseio.com',
    storageBucket: 'tpsmobile-f19f3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLANFMYBEpw2eFN6T1nFu4gZwOngtdcXU',
    appId: '1:544405577623:ios:905ebcc83a27b51c7d6ed2',
    messagingSenderId: '544405577623',
    projectId: 'tpsmobile-f19f3',
    databaseURL: 'https://tpsmobile-f19f3-default-rtdb.firebaseio.com',
    storageBucket: 'tpsmobile-f19f3.appspot.com',
    iosClientId: '544405577623-i3go96hnho2o0r3rn53h1q8uphpfcj42.apps.googleusercontent.com',
    iosBundleId: 'com.example.publicsquarenext',
  );
}
